version: '2'
volumes:
    config:
    mosquitto:
services:
  homeassistant:
    build: homeassistant
    privileged: true
    network_mode: "host"
    volumes:
      - 'config:/config'
    restart: always
  # mqtt:
  #   build: mqtt
  #   ports:
  #     - "1883:1883"
  #   restart: always
  #   volumes:
  #     - mosquitto:/mosquitto/data
  hass-configurator:
    image: "causticlab/hass-configurator-docker:latest"
    restart: always
    depends_on:
      - homeassistant
    ports:
      - "3218:3218"
    volumes:
      - 'config:/hass-config'
    environment:
      - HC_BASEPATH=/hass-config
  wifi-connect:
    build: ./wifi-connect
    network_mode: "host"
    labels:
        io.balena.features.dbus: '1'
    cap_add:
        - NET_ADMIN
    environment:
        DBUS_SYSTEM_BUS_ADDRESS: "unix:path=/host/run/dbus/system_bus_socket"
        PORTAL_SSID: "HomeSoul_captive"
        PORTAL_PASSWORD: "h0mesoul2021"
        PORTAL_LISTENING_PORT: "8080"
